apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-web-app-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      service-name: node-app
  template:
    metadata:
      labels:
        service-name: node-app
    spec:
      containers:
      - image: girishvarun/node-js-sample:1.0
        name: my-web-app
        ports:
        - containerPort: 8080
          protocol: TCP
