apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    service-name: todo-app
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30002