apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  selector:
    service-name: node-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30001