apiVersion: v1
kind: Service
metadata:
  name: datadog-agent-service
spec:
  selector:
    app: datadog-agent
  type: NodePort
  ports:
  - name: http
    protocol: UDP
    port: 8125
    targetPort: 8125
    nodePort: 30005