apiVersion: v1
kind: Pod
metadata:
  name: my-web-app-pod
  labels:
    app: node-sample-app
spec:
  containers:
  - name: my-web-app
    image: girishvarun/node-js-sample:1.0
    ports:
    - containerPort: 8080